### ISSUE TITLE
Support for tiktoken tokenizers 

### ISSUE THREAD

**Issue by KeshavSingh29** [swallow-llm/swallow-evaluation#3]
Hi there, 
Thanks for providing this amazing repo. 

I was wondering if there will be support for non-huggingface tokenizers as well in future? 

Reason: 
New models are using tiktoken tokenizers which are not supported in huggingface generation pipeline(afaik) and I wanted to evaluate my custom model pre-trained using tiktoken tokenizer.

**Comment by stjohn2007** [comment]
Thank you for your question.

At the moment, we don't have a plan to support non-Hugging Face inference pipelines or tokenizers.
This is because our policy is to use off-the-shelf frameworks such as LM Eval Harness with minimal changes, aiming to reduce the required human resources for maintenance.

If you want to evaluate your custom model using our repository, we recommend converting both your model and tokenizer to the Hugging Face format.
